// This file is generated by scripts/generate_native_client_registry.mjs.
// Source of truth: src/client-registry.mjs. Do not edit by hand.

import Foundation

enum ClientID: String, CaseIterable, Codable, Identifiable {
    case workbuddy = "workbuddy"
    case doubao = "doubao"
    case codex = "codex"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .workbuddy: return LingGlowL10n.string("WorkBuddy")
        case .doubao: return LingGlowL10n.string("豆包")
        case .codex: return LingGlowL10n.string("Codex")
        }
    }

    /// Registry-derived list used by weekly scheduling. Runtime adapter
    /// validation still gates actual assignment and reminders.
    static var schedulableCases: [ClientID] { [.workbuddy, .doubao, .codex] }
}
