import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import test from 'node:test';
import {fileURLToPath} from 'node:url';
import {CLIENT_REGISTRY, SCHEDULE_CLIENT_IDS, TARGET_CLIENT_IDS} from '../src/client-registry.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const GENERATOR = path.join(ROOT, 'scripts', 'generate_native_client_registry.mjs');
const GENERATED = path.join(ROOT, 'native', 'Sources', 'GeneratedClientRegistry.swift');
const MODELS = path.join(ROOT, 'native', 'Sources', 'Models.swift');

test('the native ClientID bridge is generated from the canonical Agent registry', () => {
  const result = spawnSync(process.execPath, [GENERATOR, '--check'], {
    cwd: ROOT,
    encoding: 'utf8',
  });
  assert.equal(result.status, 0, result.stderr || result.stdout || 'native registry bridge is stale');

  const source = fs.readFileSync(GENERATED, 'utf8');
  const models = fs.readFileSync(MODELS, 'utf8');
  assert.match(source, /generated by scripts\/generate_native_client_registry\.mjs/u);
  assert.doesNotMatch(models, /enum ClientID/u);
  for (const {id, displayName} of CLIENT_REGISTRY) {
    assert.equal(source.includes(`= ${JSON.stringify(id)}`), true);
    assert.equal(source.includes(`return LingGlowL10n.string(${JSON.stringify(displayName)})`), true);
  }
  for (const clientId of TARGET_CLIENT_IDS) {
    assert.equal(source.includes(JSON.stringify(clientId)), true);
  }
  for (const clientId of SCHEDULE_CLIENT_IDS) {
    assert.equal(source.includes(JSON.stringify(clientId)), true);
  }

  const scheduleModel = fs.readFileSync(MODELS, 'utf8');
  assert.match(scheduleModel, /private var values: \[String: WeekAssignments\]/u);
  assert.match(scheduleModel, /for client in ClientID\.allCases where decoded\[client\.rawValue\] == nil/u);
  assert.match(scheduleModel, /unknown slot returned by a newer local backend survives a read\/save cycle/u);
  assert.doesNotMatch(scheduleModel, /var codex: WeekAssignments/u);
  assert.doesNotMatch(scheduleModel, /var workbuddy: WeekAssignments/u);
  assert.doesNotMatch(scheduleModel, /var doubao: WeekAssignments/u);
});
