#!/usr/bin/env node

/**
 * Generates the small Swift bridge used by the native menu-bar app.
 *
 * `src/client-registry.mjs` remains the sole authored list of target Agents.
 * Keeping this bridge generated is deliberately preferable to letting the
 * Node service and Swift picker drift into separate client-id lists.  The
 * generated enum is still compile-time typed, so the rest of the native UI
 * retains exhaustiveness checks and safe URL construction.
 */

import {mkdir, readFile, rename, writeFile} from 'node:fs/promises';
import {dirname, resolve} from 'node:path';
import process from 'node:process';
import {CLIENT_REGISTRY} from '../src/client-registry.mjs';

const root = resolve(import.meta.dirname, '..');
const output = resolve(root, 'native/Sources/GeneratedClientRegistry.swift');
const checkOnly = process.argv.slice(2).includes('--check');
const identifier = /^[A-Za-z_][A-Za-z0-9_]*$/u;
const reserved = new Set([
  'associatedtype', 'class', 'deinit', 'enum', 'extension', 'fileprivate',
  'func', 'import', 'init', 'inout', 'internal', 'let', 'open', 'operator',
  'private', 'precedencegroup', 'protocol', 'public', 'rethrows', 'static',
  'struct', 'subscript', 'typealias', 'var', 'where', 'while', 'actor',
  'async', 'await', 'break', 'case', 'catch', 'continue', 'default', 'defer',
  'do', 'else', 'fallthrough', 'for', 'guard', 'if', 'in', 'repeat', 'return',
  'switch', 'throw', 'throws', 'try', 'as', 'Any', 'false', 'is', 'nil',
  'self', 'Self', 'super', 'true', 'Type', 'Protocol',
]);

function swiftCaseName(id) {
  const pieces = id.split('-');
  const name = pieces[0] + pieces.slice(1)
    .map((piece) => piece.slice(0, 1).toUpperCase() + piece.slice(1))
    .join('');
  if (!identifier.test(name) || reserved.has(name)) {
    throw new Error(`client registry id cannot become a safe Swift enum case: ${id}`);
  }
  return name;
}

function swiftString(value) {
  return JSON.stringify(value)
    .replaceAll('\\u2028', '\\\\u{2028}')
    .replaceAll('\\u2029', '\\\\u{2029}');
}

function render(entries) {
  if (!Array.isArray(entries) || entries.length === 0) {
    throw new Error('client registry must contain at least one target');
  }
  const seenCases = new Set();
  const rendered = entries.map((entry) => {
    if (!entry || typeof entry.id !== 'string' || typeof entry.displayName !== 'string' ||
        typeof entry.scheduleEligible !== 'boolean') {
      throw new Error('client registry entry has an unsupported shape');
    }
    const caseName = swiftCaseName(entry.id);
    if (seenCases.has(caseName)) {
      throw new Error(`client registry entries collide in Swift: ${entry.id}`);
    }
    seenCases.add(caseName);
    return {...entry, caseName};
  });

  const cases = rendered.map(({caseName, id}) => `    case ${caseName} = ${swiftString(id)}`).join('\n');
  const names = rendered.map(({caseName, displayName}) =>
    `        case .${caseName}: return LingGlowL10n.string(${swiftString(displayName)})`,
  ).join('\n');
  const schedulable = rendered.filter(({scheduleEligible}) => scheduleEligible)
    .map(({caseName}) => `.${caseName}`).join(', ');

  return `// This file is generated by scripts/generate_native_client_registry.mjs.\n` +
    `// Source of truth: src/client-registry.mjs. Do not edit by hand.\n\n` +
    `import Foundation\n\n` +
    `enum ClientID: String, CaseIterable, Codable, Identifiable {\n` +
    `${cases}\n\n` +
    `    var id: String { rawValue }\n\n` +
    `    var displayName: String {\n` +
    `        switch self {\n` +
    `${names}\n` +
    `        }\n` +
    `    }\n\n` +
    `    /// Registry-derived list used by weekly scheduling. Runtime adapter\n` +
    `    /// validation still gates actual assignment and reminders.\n` +
    `    static var schedulableCases: [ClientID] { [${schedulable}] }\n` +
    `}\n`;
}

const source = render(CLIENT_REGISTRY);
if (checkOnly) {
  let existing = '';
  try {
    existing = await readFile(output, 'utf8');
  } catch (error) {
    if (error?.code !== 'ENOENT') throw error;
  }
  if (existing !== source) {
    console.error(`Native registry bridge is stale: ${output}`);
    process.exitCode = 1;
  }
} else {
  let existing = '';
  try {
    existing = await readFile(output, 'utf8');
  } catch (error) {
    if (error?.code !== 'ENOENT') throw error;
  }
  // Do not replace an identical Swift input immediately before swiftc reads
  // it.  Keeping the inode and mtime stable also prevents parallel local QA
  // builds from tripping Swift's "input file was modified" guard.
  if (existing !== source) {
    await mkdir(dirname(output), {recursive: true});
    const temporary = `${output}.${process.pid}.tmp`;
    await writeFile(temporary, source, {encoding: 'utf8', mode: 0o644});
    await rename(temporary, output);
  }
}
